### ISSUE TITLE
apply headers with copyright/license text to source code files

### ISSUE THREAD

**Issue by mattldawson** [NCAR/aerosol-workshop-driver#29]
@jeff-cohere @bnmurphy - what do each of our organizations want in terms of copyright/licensing? NCAR typically uses Apache 2.0, but I don't think there is any problem with using another license if EPA or DOE has stricter rules. I can also include each organization in the copyright statement if you send me the text you usually use.

Remove boilerplate comments from headers as well.

**Comment by jeff-cohere** [comment]
Most DOE labs prefer the [BSD 2-](https://opensource.org/licenses/BSD-2-Clause) or [3-clause](https://opensource.org/licenses/BSD-3-Clause) licenses. I haven't asked lately how they feel about the Apache one.

Here's some license boilerplate for an open-source tool I developed with funding from Sandia:

```
//-------------------------------------------------------------------------
// Copyright (c) 2021,
// National Technology & Engineering Solutions of Sandia, LLC (NTESS).
//
// Under the terms of Contract DE-NA0003525 with NTESS, the U.S. Government
// retains certain rights in this software.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
// 1. Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright
// notice, this list of conditions and the following disclaimer in the
// documentation and/or other materials provided with the distribution.
//
// 3. Neither the name of the Sandia Corporation nor the names of the
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY SANDIA CORPORATION "AS IS" AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL SANDIA CORPORATION OR THE
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
// LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//-------------------------------------------------------------------------
```

**Comment by bnmurphy** [comment]
We use the Creative Commons license. There has been a lot of chatter about licensing software over the last 4-5 years. I think this might be mandatory for us. However, if you want to go with something different, I can make the case that I am merely contributing to this code which is distributed by other parties; it is not an EPA project.

**EPA Disclaimer**
This software/application was developed by the U.S. Environmental Protection Agency (USEPA). No warranty expressed or implied is made regarding the accuracy or utility of the system, nor shall the act of distribution constitute any such warranty. The USEPA has relinquished control of the information and no longer has responsibility to protect the integrity, confidentiality or availability of the information. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the USEPA. The USEPA seal and logo shall not be used in any manner to imply endorsement of any commercial product or activity by the USEPA or the United States Government. [<img src="https://licensebuttons.net/p/mark/1.0/88x31.png" width="50" height="15">](https://creativecommons.org/publicdomain/zero/1.0/)

**Comment by mattldawson** [comment]
I'm checking with our system admin, but I don't think there will be any problem on my end with using any of these licenses. It might be more difficult to resolve the DOE/EPA disclaimers. I guess we could include both? But, it seems like they overlap in terms of warranties, etc. How important do you think it is to include these? At least in the Apache license there is already language about there being no warranties, and I assume the same is true for these other licenses.

I was looking up Creative Commons (because I know the least about this one), and it seems like there are multiple Creative Commons licenses. @bnmurphy - does EPA have a particular one they use, or could we use any of them?
